dist: xenial
language: java
jdk: openjdk8

# looks like papa32 plugin 1.5.0 is no longer compatible with gradle 5, the other option is to try running without it
before_install:
  - wget http://services.gradle.org/distributions/gradle-4.10.2-bin.zip
  - unzip -qq gradle-4.10.2-bin.zip
  - export GRADLE_HOME=$PWD/gradle-4.10.2
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v

jobs:
  include:
    - stage: check-links
      install: npm i -g markdown-link-check
      script: markdown-link-check ./README.md
    - stage: commit-OpenAPI
      install: npm i -g swagger2openapi
      script:
        - swagger2openapi openapi/ga4gh-tool-discovery.yaml -o openapi/openapi.yaml
      after_success:
        - git checkout -B ${TRAVIS_BRANCH}
        - bash scripts/openAPI3.sh
    - stage: build_pages
      script:
      - "gradle wrapper"
      - "chmod +x gradlew"
      - "./gradlew installSwagger buildSwagger asciidoctor"
      after_success:
        - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
        - git fetch --deepen=50000
        - git branch
        - bash scripts/update-ghpages.sh
